# Generated by Django 4.2.3 on 2023-12-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='myapp_image',
        ),
    ]
